[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example_package_keshav"
dynamic = ["version"]
dependencies = ["numpy"]
readme = "README.md"

[tool.hatch.build.targets.wheel]
packages = ["src/example_package_keshav"]

[project.optional-dependencies]
test = ["pytest"]

[tool.hatch]
version.path = "src/example_package_keshav/__init__.py"